### ISSUE TITLE
Add Web MVC File to EventOnContainer Project

### ISSUE THREAD

**Issue by mike4741** [LalithaNadimpalli/EventsOnContainer#35]

**Comment by LalithaNadimpalli** [comment]
I did not understand y you created an issue...we don't have any issues in project yet..you can assign the tasks in slack not here

**Comment by mike4741** [comment]
This is where the task should be  created follow up the project progress
else it will be simply doing a project not following scram master principle
 . One of the basic lesson is to learn how to do the job using scram master
 principles
